name: Release

on:
    push:
        tags:
            - '*'
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Get version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    
            - name: Get files from repository(Gitee)
              run: |
                wget https://gitee.com/vc_teahouse/SJDM/releases/download/${{ steps.get_version.outputs.VERSION }}/%E9%9A%8F%E6%9C%BA%E7%82%B9%E5%90%8D.exe -oSJDM.exe
            - name: Upload to Release
              uses: svenstaro/upload-release-action@v2
              with:
                file: SJDM.exe