name: Release

on:
    push:
        tags:
            - '*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Get files from repository(Gitee)
              run: |
                wget https://gitee.com/vc_teahouse/SJDM/releases/download/${{ github.ref_name }}/%E9%9A%8F%E6%9C%BA%E7%82%B9%E5%90%8D.exe -SJDM.exe
            - name: Upload to Release
              uses: svenstaro/upload-release-action@v2
              with:
                file: SJDM.exe