name: Release

on:
    push:
        tags:
            - '*'
    workflow_dispatch:
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Get tags
              run: |
                echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
            - name: Get files from repository(Gitee)
              run: |
                wget https://gitee.com/vc_teahouse/SJDM/releases/download/${{ steps.tag.outputs.tag }}/%E9%9A%8F%E6%9C%BA%E7%82%B9%E5%90%8D.exe -oSJDM.exe
            - name: Upload to Release
              uses: svenstaro/upload-release-action@v2
              with:
                file: SJDM.exe
                tag: ${{ steps.tag.outputs.tag }}